// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/student.proto

package studentpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StudentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentRequest) Reset() {
	*x = StudentRequest{}
	mi := &file_proto_student_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentRequest) ProtoMessage() {}

func (x *StudentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentRequest.ProtoReflect.Descriptor instead.
func (*StudentRequest) Descriptor() ([]byte, []int) {
	return file_proto_student_proto_rawDescGZIP(), []int{0}
}

func (x *StudentRequest) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

type StudentResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int32                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Major         string                 `protobuf:"bytes,3,opt,name=major,proto3" json:"major,omitempty"`
	Email         string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	Faculty       string                 `protobuf:"bytes,5,opt,name=faculty,proto3" json:"faculty,omitempty"`
	Year          int32                  `protobuf:"varint,6,opt,name=year,proto3" json:"year,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StudentResponse) Reset() {
	*x = StudentResponse{}
	mi := &file_proto_student_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StudentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StudentResponse) ProtoMessage() {}

func (x *StudentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_student_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StudentResponse.ProtoReflect.Descriptor instead.
func (*StudentResponse) Descriptor() ([]byte, []int) {
	return file_proto_student_proto_rawDescGZIP(), []int{1}
}

func (x *StudentResponse) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *StudentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *StudentResponse) GetMajor() string {
	if x != nil {
		return x.Major
	}
	return ""
}

func (x *StudentResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *StudentResponse) GetFaculty() string {
	if x != nil {
		return x.Faculty
	}
	return ""
}

func (x *StudentResponse) GetYear() int32 {
	if x != nil {
		return x.Year
	}
	return 0
}

var File_proto_student_proto protoreflect.FileDescriptor

const file_proto_student_proto_rawDesc = "" +
	"\n" +
	"\x13proto/student.proto\x12\astudent\" \n" +
	"\x0eStudentRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\"\x8f\x01\n" +
	"\x0fStudentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x05R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05major\x18\x03 \x01(\tR\x05major\x12\x14\n" +
	"\x05email\x18\x04 \x01(\tR\x05email\x12\x18\n" +
	"\afaculty\x18\x05 \x01(\tR\afaculty\x12\x12\n" +
	"\x04year\x18\x06 \x01(\x05R\x04year2Q\n" +
	"\x0eStudentService\x12?\n" +
	"\n" +
	"GetStudent\x12\x17.student.StudentRequest\x1a\x18.student.StudentResponseB\rZ\v./studentpbb\x06proto3"

var (
	file_proto_student_proto_rawDescOnce sync.Once
	file_proto_student_proto_rawDescData []byte
)

func file_proto_student_proto_rawDescGZIP() []byte {
	file_proto_student_proto_rawDescOnce.Do(func() {
		file_proto_student_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_student_proto_rawDesc), len(file_proto_student_proto_rawDesc)))
	})
	return file_proto_student_proto_rawDescData
}

var file_proto_student_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_student_proto_goTypes = []any{
	(*StudentRequest)(nil),  // 0: student.StudentRequest
	(*StudentResponse)(nil), // 1: student.StudentResponse
}
var file_proto_student_proto_depIdxs = []int32{
	0, // 0: student.StudentService.GetStudent:input_type -> student.StudentRequest
	1, // 1: student.StudentService.GetStudent:output_type -> student.StudentResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_student_proto_init() }
func file_proto_student_proto_init() {
	if File_proto_student_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_student_proto_rawDesc), len(file_proto_student_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_student_proto_goTypes,
		DependencyIndexes: file_proto_student_proto_depIdxs,
		MessageInfos:      file_proto_student_proto_msgTypes,
	}.Build()
	File_proto_student_proto = out.File
	file_proto_student_proto_goTypes = nil
	file_proto_student_proto_depIdxs = nil
}
